import { Avatar, Box, Container, Paper, Typography } from "@mui/material";
import { Colors } from "../constants/colors";
import React, { FC } from "react";
import { Link } from "react-router-dom";
import { ArrowRightAlt } from "@mui/icons-material";
import icon1 from "../images/icon1.png";
import icon2 from "../images/icon2.png";
import icon3 from "../images/icon3.png";

const Card: FC<{
  title: string;
  c1: string;
  c2: string;
  icon: string;
}> = ({ title, c1, c2, icon }) => {
  return (
    <Paper
      sx={{
        padding: 2,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        width: 300,
        height: 300,
        border: "none",
        boxShadow: "none",
      }}
    >
      <img src={icon} alt={"icon"} />
      <Typography
        variant={"h6"}
        fontWeight={"bold"}
        color={Colors.black100}
        lineHeight={2}
      >
        {title}
      </Typography>
      <Typography
        color={Colors.blue100}
        textAlign={"center"}
        fontWeight={"bold"}
        lineHeight={2}
      >
        {c1}
      </Typography>
      <Typography textAlign={"center"} color={Colors.black100}>
        {c2}
      </Typography>
    </Paper>
  );
};

const HowItWorks = () => {
  return (
    <Container maxWidth={"xl"} sx={{ paddingY: 10 }}>
      <Box
        sx={{ display: "flex", flexDirection: "column", alignItems: "center" }}
      >
        <Typography color={Colors.blue100} variant={"h5"}>
          How it works
        </Typography>
        <Typography
          variant={"h3"}
          fontWeight={"bold"}
          width={480}
          textAlign={"center"}
          color={Colors.black100}
        >
          Why deposit can protect your assets
        </Typography>
      </Box>
      <Box
        sx={{
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          marginTop: 6,
        }}
      >
        <Card
          title={"Risk-Averse Data Model"}
          c1={"a measured risk-averse data model"}
          c2={"Deposit is a precisely measured risk-averse data model"}
          icon={icon1}
        />
        <Card
          title={"Optimize your assets"}
          c1={"optimize the allocation of assets"}
          c2={
            "Optimize the allocation of your assets and stay your assets safe when having no time or energy to manage your crypto assets."
          }
          icon={icon2}
        />
        <Card
          title={"Take advantage of the gains"}
          c1={"the gains generated by the allocation"}
          c2={
            "Take advantage of the gains generated by the allocation to counteract the risk of a decline in currency prices"
          }
          icon={icon3}
        />
      </Box>
    </Container>
  );
};

export default HowItWorks;
