import React from "react";
import { Box, Container, Typography } from "@mui/material";
import { Colors } from "../constants/colors";
import logo_black from "../images/logo_black.png";
import { Link } from "react-router-dom";
import { ROUTERS } from "../routes";
import discord from "../images/discord.png";
import github from "../images/github.png";
import twitter from "../images/twitter.png";
import discord_green from "../images/discord_green.png";

const PageFooter = () => {
  return (
    <Box width={"100%"} height={700} sx={{ mt: 4 }}>
      <Box
        sx={{
          background: "linear-gradient(to right, #022BDB, #1A4CFF)",
          height: 300,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Typography variant={"h3"} color={"white"}>
          Join of our community
        </Typography>
        <Box
          sx={{
            mt: 2,
            display: "flex",
            flexDirection: "row",
            backgroundColor: "white",
            borderRadius: 2,
            width: 420,
            alignItems: "center",
            padding: 2,
          }}
        >
          <img width={33} src={discord_green} alt={"discord_green"} />
          <a
            href={"https://discord.gg/XPXU7Bsde5"}
            target={"_blank"}
            style={{ textDecoration: "none" }}
            rel={"noreferrer noopenner"}
          >
            <Typography sx={{ ml: 1 }} color={Colors.grey20}>
              https://discord.gg/XPXU7Bsde5
            </Typography>
          </a>
        </Box>
      </Box>
      <Box sx={{ paddingBottom: 10 }}>
        <Container
          maxWidth={"xl"}
          sx={{
            borderBottom: "1px solid grey",
            display: "flex",
            flexDirection: "row",
            alignItems: "flex-start",
            justifyContent: "space-between",
            gap: 20,
            paddingY: 10,
          }}
        >
          <Box sx={{ flex: 1 }}>
            <img src={logo_black} alt={"logo_black"} />
            <Typography color={Colors.grey20} sx={{ marginTop: 5 }}>
              Deposit optimizes your asset allocation through an accurately
              measured risk-adverse data model, using the gains generated by the
              allocation to counteract the risk of currency price declines.
            </Typography>
            <Box
              sx={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "space-between",
                alignItems: "center",
                width: 160,
                mt: 2,
              }}
            >
              <a
                href={"https://github.com/Oasis-Hackathon-2022"}
                target={"_blank"}
                rel={"noreferrer noopenner"}
              >
                <img height={14} src={github} />
              </a>
              <a
                href={"https://discord.gg/XPXU7Bsde5"}
                target={"_blank"}
                rel={"noreferrer noopenner"}
              >
                <img height={14} src={discord} />
              </a>
              <a
                href={"https://twitter.com"}
                target={"_blank"}
                rel={"noreferrer noopenner"}
              >
                <img height={14} src={twitter} />
              </a>
            </Box>
          </Box>
          <Box sx={{ flex: 1 }}>
            <Typography color={Colors.black10}>About Us</Typography>
            <Link
              to={ROUTERS.OUR_STORY}
              style={{ textDecoration: "none" }}
              onClick={() => window.scrollTo(0, 0)}
            >
              <Typography
                sx={{ marginTop: 5 }}
                color={Colors.grey20}
                lineHeight={2}
              >
                Our Story
              </Typography>
            </Link>
            <a
              href={"https://deposit-1.gitbook.io/deposit-docs/"}
              target={"_blank"}
              style={{ textDecoration: "none" }}
              rel={"noreferrer noopenner"}
            >
              <Typography color={Colors.grey20} lineHeight={2}>
                White Paper
              </Typography>
            </a>
            <a
              href={"https://twitter.com"}
              target={"_blank"}
              rel={"noreferrer noopenner"}
              style={{ textDecoration: "none" }}
            >
              <Typography color={Colors.grey20} lineHeight={2}>
                Talk To Us
              </Typography>
            </a>
          </Box>
          <Box sx={{ flex: 1 }}>
            <Typography color={Colors.black10}>Our Support Download</Typography>
            <Typography sx={{ marginTop: 5 }} color={Colors.grey20}>
              No.30, Shuangqing Road, Haidian District, Beijing, China
            </Typography>
            <Typography color={Colors.grey20} sx={{ mt: 2 }}>
              Email: depositcrypto0@gmail.com
            </Typography>
          </Box>
        </Container>
        <Typography textAlign={"center"} sx={{ mt: 5, mb: 5 }}>
          © 2022 Deposit All Rights Reserved.
        </Typography>
      </Box>
    </Box>
  );
};

export default PageFooter;
